name: good_news
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  flutter_dotenv: ^5.1.0
  tcard: ^1.3.5
  app_settings: ^6.1.1
  crypto: ^3.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.2.4
  image_picker: ^1.2.0
  flutter_card_swiper: ^7.0.2
  permission_handler: ^12.0.1
  share_plus: ^12.0.0
  intl: ^0.20.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  http: ^1.5.0
  card_swiper: ^3.0.1
  video_player: ^2.10.1
  timeago: ^3.7.1
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/splash_animation.json



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/new_logo_goodnews.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/new_logo_goodnews.png"